version: 2.1

jobs:
  checkout:
    working_directory: ~/backend
    docker:
      - image: circleci/node:12.22-browsers
    steps:
      - checkout
      - save_cache:
          key: v0-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/backend
  dependencies:
    working_directory: ~/backend
    docker:
      - image: circleci/node:12.22-browsers
    steps:
      - restore_cache:
          key: v0-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: checking version
          command: npm --version

      - run:
          name: Install dependencies
          command: npm install --no-optional
      - save_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/backend/node_modules
  lint:
    working_directory: ~/backend
    docker:
      - image: circleci/node:12.22-browsers
    steps:
      - restore_cache:
          key: v0-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: ESLint
          command: npm run lint
      # - run:
      #     name: Prettier
      #     command: npm run prettier:check
  test:
    working_directory: ~/backend
    docker:
      - image: circleci/node:12.22-browsers
      - image: circleci/postgres:12
        environment:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: ntwari
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: electrica
    steps:
      - restore_cache:
          key: v0-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Test
          command: npm run test
      - run:
          name: Copy .env
          command: cp .env.example .env
      - run:
          name: Wait for Postgres to start
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: E2E
          command: npm run test
  build:
    working_directory: ~/backend
    docker:
      - image: circleci/node:12.22-browsers
    steps:
      - restore_cache:
          key: v0-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v0-node-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npm run build
      - save_cache:
          key: v0-build-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/backend/dist/backend

workflows:
  version: 2
  ci:
    jobs:
      - checkout
      - dependencies:
          requires:
            - checkout
      - lint:
          requires:
            - dependencies
      - test:
          requires:
            - lint
      - build:
          requires:
            - test